name: Generate Allure Report 
on: 
  workflow_dispatch:

# Can have multiple jobs, but this example is just one build job.
jobs:
  run-batch:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - uses: cryptic-wizard/run-behave-tests@v0.4.0
      - name: Install pytest Allure plugin
        run: pip install pytest allure-pytest
      - name: Generate Allure test report
        run: behave -f allure_behave.formatter:AllureFormatter -o ${{vars.ALLURE_RESULTS_PATH}} -D browser=
