name: Run Automation on Ubuntu 
on: 
  workflow_dispatch:

# Can have multiple jobs, but this example is just one build job.
jobs:
  run-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - name: install behave
        run: pip install git+https://github.com/behave/behave
      - name: run the behave command  
        run: behave
