name: Run Automation on Multiple OS version

on: 
  workflow_dispatch:
   inputs:
      os:
        description: 'Type of OS (ubuntu-latest, macos-latest, windows-latest)'
        required: true
        default: 'ubuntu-latest'
jobs:
  test: 
    runs-on: ${{ github.event.inputs.os }}    
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: install python 
        uses: actions/setup-python@v5
        with: 
          python-version: 3.10.5
      - name: install and run behave 
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-path: Logs
          test-output-name: ${{ github.event.inputs.os }}.txt

