name: Run Batch File 
on: 
  workflow_dispatch:

# Can have multiple jobs, but this example is just one build job.
jobs:
  run-batch:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.5
      - uses: cryptic-wizard/run-behave-tests@v0.4.0
      - name: Install pytest Allure plugin
        run: pip install pytest allure-pytest
      - name: List directory contents (debugging)
        run: dir
        shell: cmd
      - name: Run Automation Tests
        run: run.bat
        shell: cmd
