name: Run Batch File 
on: push

# Can have multiple jobs, but this example is just one build job.
jobs:
  run-batch:
    runs-on: windows-latest
    steps:
     - name: List directory contents (debugging)
       run: dir
       shell: cmd
       
     - name: Build ROM
       run: run.bat
       shell: cmd
